names(ftregion)
ftregion<-read.csv("ftregion.txt",sep=";",header=T)
ftregion<-read.csv("ftcomuna.txt",sep=";",header=T)
ftis<-read.csv("ftiniciosintomas.txt",sep=";",header=T)
summary(ftis)
table(ftis$fch_publicacion)

ftis2=ftis[which(ftis$fch_publicacion=="2020-10-26"),]
ftis3=ftregion[which(ftregion$id_region==4),]
ftis3
names(ftis3)
View(ftis3)
table(ftis3)
ftis3=ftis2[which(ftis2$id_region==2),]
ftis3
length(ftis3)
t1=aggregate(cant_casosconfirmados~id_semanaepidemiologica,ftis3,sum)
t1
t2=aggregate(cant_casosconfirmadoschowellw5~id_semanaepidemiologica,ftis3,sum)
t2
plot(t1[,1],t1[,2],type="l")
lines(t2[,1],t2[,2],col="red")